epsilon_svgd: 0.08 # Pas de mise à jour des particules
gamma: 0.015 # Ponderation de l'attraction vers les zones de haute densité
#bandwith_kernel: 0.001 # Largeur de bande du noyau RBF (None => heuristique de mediane)