defaults:
  - problem: qubo
  - agent: reinforce
  - _self_

# génériques
seed: 0
verbose: true
output_dir: outputs
nb_instances_test: 10
nb_restarts: 10
budget: 10000
lambda: 20
visualization: true
learning_rate_svgd: 0.01
