defaults:
  - problem: nk3 # qubo / nk / blockwise
  - agent: reinforce
  - _self_

# génériques
seed: 0
verbose: true
output_dir: outputs
nb_instances_test: 10
nb_restarts: 10
budget: 50000
visualization: false

strategy_variants:
  - label: Baseline
    advantage: baseline
  - label: Global rank weighted
    advantage: globalrankweighted
  - label: Per-agent rank weighted
    advantage: peragentrankweighted
  - label: Normalized fitness
    advantage: normalizedfitness
