name: REINFORCE-EDA
updateMethod: REINFORCE
M: 10
lambda: 10
advantage: peragentrankweighted # peragentrankweighted | globalrankweighted | baseline | normalizedfitness | baseline_rescaled
kernel:  rbf # rbf | no_interact
epsilon_svgd: 0.06 # Pas de mise à jour des particules
gamma: 0.006 # Ponderation de l'attraction vers les zones de haute densité
no_interact: false
no_repulsion: false
enable_greedy_final: true
decay_start_ratio: 0.1
min_factor: 0.1
decay: true
ppo_active: true
