name: REINFORCE-EDA
updateMethod: REINFORCE
M: 7
lambda: 13
advantage: globalrankweighted # peragentrankweighted | globalrankweighted | baseline | normalizedfitness | baseline_rescaled
kernel:  rbf # rbf | hk | pk | ppk | jsd | fr | no_interact
no_interact: false
no_repulsion: false
enable_greedy_final: false
decay_start_ratio: 0.03
min_factor: 0.1
decay: true
adaptive_lambda: false
lr_lambda: 0.25
