name: REINFORCE-EDA
updateMethod: REINFORCE
M: 4
lambda: 10
advantage: globalrankweighted # peragentrankweighted | globalrankweighted | baseline | normalizedfitness | baseline_rescaled
kernel:  fr # rbf | hk | pk | ppk | jsd | fr | no_interact
no_interact: false
no_repulsion: false
decay_start_ratio: 0.05
min_factor: 0.05
decay: true