name: REINFORCE-EDA
updateMethod: REINFORCE
M: 3
lambda: 25
advantage: peragentrankweighted # peragentrankweighted | globalrankweighted | baseline | normalizedfitness
kernel:  rbf # rbf | hk | pk | ppk | jsd
no_interact: false
